/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package veterinaria.view;

import java.awt.BorderLayout;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import veterinaria.businesslogic.dao.AgendaDAO;
import veterinaria.businesslogic.dao.CitaDAO;
import veterinaria.businesslogic.dao.DuenoDAO;
import veterinaria.businesslogic.dao.FechaHoraDAO;
import veterinaria.businesslogic.dao.MascotaDAO;
import veterinaria.businesslogic.dao.VeterinarioDAO;
import veterinaria.businesslogic.dto.CitaDTO;
import veterinaria.businesslogic.dto.DuenoDTO;
import veterinaria.businesslogic.dto.MascotaDTO;
import veterinaria.businesslogic.dto.VeterinarioDTO;

/**
 *
 * @author gabosaurio
 */
public class GUIAgendarCita extends javax.swing.JFrame {

    private java.sql.Date fechaSQL;
    /**
     * Creates new form GUIAgendarCita
     */
    
    private static final Logger logger = LogManager.getLogger(GUIAgendarCita.class);
    
    public GUIAgendarCita() {
        initComponents();
        comboMascotas.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboVeterinarios.setModel(new DefaultComboBoxModel<>());
        initDatePicker();
        setComboMascotas();
        setComboVeterinarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textFieldMotivo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        comboMascotas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboVeterinarios = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboHoras = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ineLabel = new javax.swing.JLabel();
        especieLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agendar Cita");

        jLabel2.setText("Motivo de la cita");

        textFieldMotivo.setColumns(20);
        textFieldMotivo.setRows(5);
        jScrollPane1.setViewportView(textFieldMotivo);

        jLabel3.setText("Mascota");

        comboMascotas.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMascotasActionPerformed(evt);
            }
        });

        jLabel4.setText("INE");

        jLabel6.setText("Veterinario");

        comboVeterinarios.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabel7.setText("Hora");

        comboHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        comboHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHorasActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jLabel5.setText("Especie");

        ineLabel.setText("DueñoINE");

        especieLabel.setText("MascotaEspecie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboMascotas, 0, 425, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ineLabel)
                                            .addComponent(especieLabel))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboVeterinarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboHoras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addGap(68, 68, 68)
                .addComponent(botonGuardar)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ineLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(especieLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboVeterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonGuardar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTextData() {
        MascotaDTO mascota = (MascotaDTO) comboMascotas.getSelectedItem();
        try {
            DuenoDTO dueno = new DuenoDAO().obtenerPorId(mascota.getIdDuenio());
            ineLabel.setText(dueno.getIne());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al recopilar dueño");
            logger.error("Error al recopilar Dueño: ", ex);
        }
        especieLabel.setText(mascota.getEspecie());
    }
    
    private void initDatePicker() {
        UtilDateModel model = new UtilDateModel();
        Properties p = new Properties();
        p.put("text.today", "Hoy");
        p.put("text.month", "Mes");
        p.put("text.year", "Año");

        JDatePanelImpl datePanel = new JDatePanelImpl(model);
        JDatePickerImpl datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(datePicker, BorderLayout.CENTER);

        jPanel1.revalidate();
        jPanel1.repaint();
        
        datePicker.addActionListener(e -> {
            String selectedDate = datePicker.getJFormattedTextField().getText();
            if (selectedDate != null) {
                setComboHoras(selectedDate);
            }
        });
    }
    
    private void setComboMascotas() {
        List<MascotaDTO> mascotas = null;
        try {
            mascotas = new MascotaDAO().obtenerTodos();
        } catch (SQLException ex) {
            logger.error("Error al recopilar Mascotas", ex);
        }
        
        for (MascotaDTO mascota : mascotas) {
            comboMascotas.addItem(mascota);
        }
    }
    
    private void setComboVeterinarios() {
        List<VeterinarioDTO> veterinarios = new VeterinarioDAO().seleccionarTodosLosVeterinarios();
        
        for (VeterinarioDTO veterinario : veterinarios) {
            comboVeterinarios.addItem(veterinario);
        }
    }
    
    public void setComboHoras(String fecha) {
        VeterinarioDTO veterinario = (VeterinarioDTO) comboVeterinarios.getSelectedItem();
        int agendaVet = veterinario.getAgenda();
        
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date fechaUtil = null;
        try {
            fechaUtil = formato.parse(fecha);
        } catch (ParseException ex) {
            logger.error("Error al formatear fecha", ex);
        }
        
        fechaSQL = new java.sql.Date(fechaUtil.getTime());
        List<String> horas = new AgendaDAO().obtenerCitasDisponibles(fechaSQL, agendaVet);
        
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(horas.toArray(new String[0]));
        comboHoras.setModel(modelo);
    }
    
    private void comboHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHorasActionPerformed

    public void getTextFieldsData(CitaDTO cita) {
        cita.setMotivoDeConsulta(textFieldMotivo.getText());
        cita.setEstadoDeCita("Pendiente");
        MascotaDTO mascota = (MascotaDTO) comboMascotas.getSelectedItem();
        cita.setIdMascota(mascota.getIdMascota());
        VeterinarioDTO veterinario = (VeterinarioDTO) comboVeterinarios.getSelectedItem();
        cita.setIdDueno(mascota.getIdDuenio());
        cita.setIdAgenda(veterinario.getAgenda());
        cita.setIdFechaHora(new FechaHoraDAO().getFechaIdPorFechaHora(fechaSQL, 
                (String) comboHoras.getSelectedItem(), 
                veterinario.getAgenda()));
    }
    
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        CitaDTO cita = new CitaDTO();
        getTextFieldsData(cita);
        if (new CitaDAO().insertarCita(cita)) {
            JOptionPane.showMessageDialog(this, "Se agendó cita con éxito!");
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        GUIMenuPrincipal controlador = new GUIMenuPrincipal();
        controlador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void comboMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMascotasActionPerformed
        setTextData();
    }//GEN-LAST:event_comboMascotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAgendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAgendarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JComboBox<String> comboHoras;
    private javax.swing.JComboBox<MascotaDTO> comboMascotas;
    private javax.swing.JComboBox<VeterinarioDTO> comboVeterinarios;
    private javax.swing.JLabel especieLabel;
    private javax.swing.JLabel ineLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textFieldMotivo;
    // End of variables declaration//GEN-END:variables
}
