package veterinaria.view;

/**
 *
 * @author User
 */
public class GUIMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuPrincipal
     */
    public GUIMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonMascotas = new javax.swing.JButton();
        botonDuenos = new javax.swing.JButton();
        compraBoton = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        botonAgendarCita = new javax.swing.JButton();
        botonConsultarCitas = new javax.swing.JButton();
        botonVeterinarios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 500));
        setPreferredSize(new java.awt.Dimension(550, 300));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Sistema Veterinaria");
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 110));

        botonMascotas.setText("Mascotas");
        botonMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMascotasActionPerformed(evt);
            }
        });

        botonDuenos.setText("Dueños");
        botonDuenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDuenosActionPerformed(evt);
            }
        });

        compraBoton.setText("Compra de productos");
        compraBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraBotonActionPerformed(evt);
            }
        });

        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        botonAgendarCita.setText("Agendar Cita");
        botonAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgendarCitaActionPerformed(evt);
            }
        });

        botonConsultarCitas.setText("Consultar Citas");
        botonConsultarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarCitasActionPerformed(evt);
            }
        });

        botonVeterinarios.setText("Veterinarios");
        botonVeterinarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVeterinariosActionPerformed(evt);
            }
        });

        jButton1.setText("Productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVeterinarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonDuenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compraBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonConsultarCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAgendarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonDuenos)
                        .addGap(18, 18, 18)
                        .addComponent(botonVeterinarios)
                        .addGap(18, 18, 18)
                        .addComponent(botonMascotas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(compraBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgendarCita)
                        .addGap(18, 18, 18)
                        .addComponent(botonConsultarCitas)))
                .addGap(31, 31, 31)
                .addComponent(botonCerrar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMascotasActionPerformed
        GUICRUDMascotas controlador = new GUICRUDMascotas();
        controlador.llenarTabla();
        controlador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonMascotasActionPerformed

    private void compraBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraBotonActionPerformed
        GUICompraProductos controlador = new GUICompraProductos();
        controlador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_compraBotonActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgendarCitaActionPerformed
        GUIAgendarCita controlador = new GUIAgendarCita();
        controlador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAgendarCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void botonDuenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDuenosActionPerformed
        GUICRUDDueno controladorDueno = new GUICRUDDueno();
        controladorDueno.llenarTablaDuenos();
        controladorDueno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonDuenosActionPerformed

    private void botonConsultarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarCitasActionPerformed
        GUIConsultarCitas controlador = new GUIConsultarCitas();
        controlador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonConsultarCitasActionPerformed

    private void botonVeterinariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVeterinariosActionPerformed
        GUICRUDVeterinario controladorVeterinario = new GUICRUDVeterinario();
        controladorVeterinario.llenarTablaVeterinarios();
        controladorVeterinario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVeterinariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUICRUDProducto controladorProductos = new GUICRUDProducto();
        controladorProductos.llenarTablaProductos();
        controladorProductos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgendarCita;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonConsultarCitas;
    private javax.swing.JButton botonDuenos;
    private javax.swing.JButton botonMascotas;
    private javax.swing.JButton botonVeterinarios;
    private javax.swing.JButton compraBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
