package veterinaria.view;

import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import veterinaria.businesslogic.dao.DireccionDuenoDAO;
import veterinaria.businesslogic.dao.DuenoDAO;
import veterinaria.businesslogic.dto.DireccionDuenoDTO;
import veterinaria.businesslogic.dto.DuenoDTO;

/**
 *
 * @author User
 */
public class GUIRegistroDueno extends javax.swing.JFrame {

    private static final Logger logger = LogManager.getLogger(GUIRegistroDueno.class);
    private DuenoDTO duenoParaEditar;
    private DireccionDuenoDTO direccionParaEditar;
    private boolean modoEdicion = false;
    
    public GUIRegistroDueno(){
        initComponents();
    }
    
    public GUIRegistroDueno(DuenoDTO dueno, DireccionDuenoDTO direccion) {
        initComponents();
        this.duenoParaEditar = dueno;
        this.direccionParaEditar = direccion;
        this.modoEdicion = true;
        llenarCamposParaEdicion();
        configurarVentanaParaEdicion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNombreDueno = new javax.swing.JTextField();
        textTelefonoDueno = new javax.swing.JTextField();
        textCorreoDueno = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textCalle = new javax.swing.JTextField();
        textColonia = new javax.swing.JTextField();
        textNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textINE = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(356, 375));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Telefono:");

        jLabel3.setText("Correo:");

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Datos del Dueño");

        jLabel5.setText("Calle");

        jLabel6.setText("Colonia");

        jLabel7.setText("Numero");

        jLabel8.setText("INE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonGuardar)
                        .addGap(59, 59, 59)
                        .addComponent(botonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(20, 20, 20))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textINE)
                            .addComponent(textNombreDueno)
                            .addComponent(textTelefonoDueno)
                            .addComponent(textCorreoDueno, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(textCalle)
                            .addComponent(textColonia)
                            .addComponent(textNumero))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNombreDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textTelefonoDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCorreoDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textINE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonCancelar))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if (textNombreDueno.getText().trim().isEmpty() || textTelefonoDueno.getText().trim().isEmpty() || 
            textCorreoDueno.getText().trim().isEmpty() || textCalle.getText().trim().isEmpty() || 
            textColonia.getText().trim().isEmpty() || textNumero.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campos incompletos, llene todos los campos por favor");
            return;
        }

        try {
            if (modoEdicion) {
                actualizarDueno();
            } else {
                registrarNuevoDueno();
            }
        } catch (SQLException ex) {
            logger.error("Error en GUIRegistroDueno.botonGuardarActionPerformed", ex);
            JOptionPane.showMessageDialog(this, "Error inesperado: " + ex.getMessage(), 
                                           "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed
    
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        regresarACRUD();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void limpiarCampos(){
        textNombreDueno.setText("");
        textTelefonoDueno.setText("");
        textCorreoDueno.setText("");
        textCalle.setText("");
        textColonia.setText("");
        textNumero.setText("");
    }
    
    private void llenarCamposParaEdicion() {
        if (duenoParaEditar != null) {
            textNombreDueno.setText(duenoParaEditar.getNombreCompleto());
            textTelefonoDueno.setText(duenoParaEditar.getTelefono());
            textCorreoDueno.setText(duenoParaEditar.getEmail());
        }

        if (direccionParaEditar != null) {
            textCalle.setText(direccionParaEditar.getCalle());
            textColonia.setText(direccionParaEditar.getColonia());
            textNumero.setText(direccionParaEditar.getNumero());
        }
    }
    
    private void registrarNuevoDueno() throws SQLException {
        DuenoDAO daoDueno = new DuenoDAO();
        DireccionDuenoDAO daoDireccion = new DireccionDuenoDAO();

        DuenoDTO dtoDueno = new DuenoDTO();
        DireccionDuenoDTO dtoDireccion = new DireccionDuenoDTO();

        dtoDueno.setNombreCompleto(textNombreDueno.getText().trim());
        dtoDueno.setTelefono(textTelefonoDueno.getText().trim());
        dtoDueno.setEmail(textCorreoDueno.getText().trim());
        dtoDueno.setIne(textINE.getText().trim());

        int resultadoDueno = daoDueno.insertar(dtoDueno);

        if (resultadoDueno > 0) {
            int idDuenio = dtoDueno.getIdDuenio();

            dtoDireccion.setCalle(textCalle.getText().trim());
            dtoDireccion.setColonia(textColonia.getText().trim());
            dtoDireccion.setNumero(textNumero.getText().trim());
            dtoDireccion.setIdDuenio(idDuenio);

            boolean resultadoDireccion = daoDireccion.insertarDireccion(dtoDireccion);

            if (resultadoDireccion) {
                JOptionPane.showMessageDialog(this, "Dueño y dirección registrados exitosamente");
                regresarACRUD();
            } else {
                JOptionPane.showMessageDialog(this, "El dueño se registró pero hubo un problema al registrar la dirección", 
                                         "Advertencia", JOptionPane.WARNING_MESSAGE);
                logger.warn("Error al registrar dirección en GUIRegistroDueno.botonGuardarActionPerformed");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar al dueño", 
                                     "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void actualizarDueno() throws SQLException {
        DuenoDAO daoDueno = new DuenoDAO();
        DireccionDuenoDAO daoDireccion = new DireccionDuenoDAO();

        duenoParaEditar.setNombreCompleto(textNombreDueno.getText().trim());
        duenoParaEditar.setTelefono(textTelefonoDueno.getText().trim());
        duenoParaEditar.setEmail(textCorreoDueno.getText().trim());

        int resultadoDueno = daoDueno.actualizar(duenoParaEditar);

        if (resultadoDueno > 0) {
            boolean resultadoDireccion = true;

            if (direccionParaEditar != null) {
                
                direccionParaEditar.setCalle(textCalle.getText().trim());
                direccionParaEditar.setColonia(textColonia.getText().trim());
                direccionParaEditar.setNumero(textNumero.getText().trim());

                resultadoDireccion = daoDireccion.actualizarDireccion(direccionParaEditar);
            } else {
                
                DireccionDuenoDTO nuevaDireccion = new DireccionDuenoDTO();
                nuevaDireccion.setCalle(textCalle.getText().trim());
                nuevaDireccion.setColonia(textColonia.getText().trim());
                nuevaDireccion.setNumero(textNumero.getText().trim());
                nuevaDireccion.setIdDuenio(duenoParaEditar.getIdDuenio());

                resultadoDireccion = daoDireccion.insertarDireccion(nuevaDireccion);
            }

            if (resultadoDireccion) {
                JOptionPane.showMessageDialog(this, "Dueño actualizado exitosamente");
                regresarACRUD();
            } else {
                JOptionPane.showMessageDialog(this, "El dueño se actualizó pero hubo un problema con la dirección", 
                                       "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar al dueño", 
                                   "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void configurarVentanaParaEdicion() {
        if (modoEdicion) {
            setTitle("Editar Dueño");
            jLabel4.setText("Editar Datos del Dueño");
            botonGuardar.setText("Actualizar");
        }
    }
    
    private void regresarACRUD() {
        GUICRUDDueno controladorDueno = new GUICRUDDueno();
        controladorDueno.llenarTablaDuenos();
        controladorDueno.setVisible(true);
        this.dispose();
    }
    
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textCalle;
    private javax.swing.JTextField textColonia;
    private javax.swing.JTextField textCorreoDueno;
    private javax.swing.JTextField textINE;
    private javax.swing.JTextField textNombreDueno;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textTelefonoDueno;
    // End of variables declaration//GEN-END:variables
}
